// Code generated by MockGen. DO NOT EDIT.
// Source: internal/sample_app/application/repository/sample_repository_interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/sample_app/application/repository/sample_repository_interface.go -destination=internal/sample_app/application/repository/sample_repository_mock.go -package=repository -mock_names=ISampleRepository=MockSampleRepository
//

// Package repository is a generated GoMock package.
package repository

import (
	transaction "modern-dev-env-app-sample/internal/sample_app/application/repository/transaction"
	sample "modern-dev-env-app-sample/internal/sample_app/domain/entity/sample"
	value "modern-dev-env-app-sample/internal/sample_app/domain/value"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSampleRepository is a mock of ISampleRepository interface.
type MockSampleRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSampleRepositoryMockRecorder
}

// MockSampleRepositoryMockRecorder is the mock recorder for MockSampleRepository.
type MockSampleRepositoryMockRecorder struct {
	mock *MockSampleRepository
}

// NewMockSampleRepository creates a new mock instance.
func NewMockSampleRepository(ctrl *gomock.Controller) *MockSampleRepository {
	mock := &MockSampleRepository{ctrl: ctrl}
	mock.recorder = &MockSampleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSampleRepository) EXPECT() *MockSampleRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockSampleRepository) Delete(sample *sample.Sample, iTx transaction.ITransaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", sample, iTx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSampleRepositoryMockRecorder) Delete(sample, iTx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSampleRepository)(nil).Delete), sample, iTx)
}

// FindAll mocks base method.
func (m *MockSampleRepository) FindAll(iTx transaction.ITransaction) ([]*sample.Sample, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", iTx)
	ret0, _ := ret[0].([]*sample.Sample)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockSampleRepositoryMockRecorder) FindAll(iTx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockSampleRepository)(nil).FindAll), iTx)
}

// FindByIDs mocks base method.
func (m *MockSampleRepository) FindByIDs(ids value.SampleIDs, iTx transaction.ITransaction) ([]*sample.Sample, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIDs", ids, iTx)
	ret0, _ := ret[0].([]*sample.Sample)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByIDs indicates an expected call of FindByIDs.
func (mr *MockSampleRepositoryMockRecorder) FindByIDs(ids, iTx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIDs", reflect.TypeOf((*MockSampleRepository)(nil).FindByIDs), ids, iTx)
}

// Save mocks base method.
func (m *MockSampleRepository) Save(sample *sample.Sample, iTx transaction.ITransaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", sample, iTx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockSampleRepositoryMockRecorder) Save(sample, iTx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockSampleRepository)(nil).Save), sample, iTx)
}
